# Generated by Django 3.2.6 on 2021-08-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210809_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
