# Generated by Django 3.2.6 on 2021-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currently_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fash', 'Fashion'), ('toys', 'Toys'), ('elec', 'Electronics'), ('home', 'Home'), ('sport', 'Sports'), ('other', 'Other'), ('', '---')], default='', max_length=11, verbose_name='Category (optional)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='200 characters max.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/auctions', verbose_name='Upload an Image (optional)'),
        ),
    ]
