# Generated by Django 3.2.6 on 2021-08-10 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210810_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bid Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comment Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
