# Generated by Django 3.2.6 on 2021-08-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210810_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='auctions', verbose_name='Upload an Image (optional)'),
        ),
    ]
