# Generated by Django 3.2.6 on 2021-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Starting Price $'),
        ),
    ]
