# Generated by Django 3.2.6 on 2021-08-12 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 58, 51, 184517, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
