# Generated by Django 3.2.6 on 2021-08-14 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
