# Generated by Django 3.2.6 on 2021-08-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210814_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_price',
            new_name='starting_bid',
        ),
    ]
