# Generated by Django 3.2.6 on 2021-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_starting_price_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fash', 'Fashion'), ('toys', 'Toys'), ('elec', 'Electronics'), ('home', 'Home'), ('sport', 'Sports'), ('other', 'Other'), ('', '---')], max_length=11, verbose_name='Category (optional)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Starting Bid $'),
        ),
    ]
