# Generated by Django 3.2.6 on 2021-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20210816_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fash', 'Fashion'), ('toys', 'Toys'), ('elec', 'Electronics'), ('home', 'Home'), ('sport', 'Sports'), ('other', 'Other')], max_length=11, verbose_name='Category (optional)'),
        ),
    ]
