# Generated by Django 3.2.6 on 2021-08-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='price',
        ),
    ]
